[tool.poetry]
name = "makenew-pypackage"
version = "3.1.0"
description = "Package skeleton for a Python module."
authors = ["Evan Sosenko <razorx@evansosenko.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/makenew/pypackage"
repository = "https://github.com/makenew/pypackage"
include = ['poetry.lock']

[tool.poetry.dependencies]
python = "~3.9.6"

[tool.poetry.dev-dependencies]
black = "^21.4b1"
bump2version = "^1.0.0"
pylint = "^2.4.0"
pytest = "^6.0.0"
pytest-cov = "^2.8.0"
pytest-incremental = "^0.6.0"
pytest-runner = "^5.2.0"
pytest-watch = "^4.2.0"
twine = "^3.0.0"
wheel = "^0.34.0"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
